"""Updated book_id field in booking

Revision ID: af349ce284c0
Revises: bb7e48918f87
Create Date: 2018-12-11 14:16:11.941846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af349ce284c0'
down_revision = 'bb7e48918f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_booking_book_id'), 'booking', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_book_id'), table_name='booking')
    # ### end Alembic commands ###
